on:
  push:
    branches:
      - main
name: dev
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build:js
      - name: Upload
        run: npm run upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_DEV }}
          S3_REGION: us-east-1
          S3_UPLOAD_CONCURRENCY: 20
