on:
  push:
    branches:
      - main
  release:
    types:
      - created

name: npm

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build && cp -r bin dist
      - name: Publish
        uses: decentraland/oddish-action@master
        with:
          access: public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
